nodeLinker: node-modules
npmRegistryServer: https://registry.yarnpkg.com

npmScopes:
  sandbox-as-a-service:
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    # npmAuthToken: ${NPM_TOKEN}
