name: Publish Package

permissions:
  contents: read
  packages: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Enable Corepack & hydrate Yarn 4.6.0
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install
        env:
          NPM_TOKEN: ${{ secrets.ORG_PAT_READ_PACKAGES }} # Consider defining at the job level if needed in multiple steps

      - name: Build
        run: yarn build

      - name: Publish to GitHub Packages
        run: yarn publish
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
